### ISSUE TITLE
 Release into PyPI

### ISSUE THREAD

**Issue by esteve** [colcon/colcon-cargo#22]
Once we're happy with the feature set, we should release `colcon-cargo` into PyPI

Particularly, when `colcon-cargo` is fully integrated into `colcon test`, it would be a good time for a release

**Comment by stelzo** [comment]
It would be great to publish it using SemVer to indicate feature parity.

A published package would make it possible to integrate Cargo dependencies into rosdep (https://github.com/ros-infrastructure/rosdep/pull/923), which could greatly reduce Rust related overhead for non-Rust-speaking users that just want to build a binary package.

**Comment by luca-della-vedova** [comment]
Hi @stelzo!

I had a chat with the maintainers and they mentioned that they would like to see at least better coverage and testing in the library before publishing it, to show that the library is working as intended (which is why I've been taking that direction with #35 and #39

**Comment by luca-della-vedova** [comment]
Everything is unblocked now, at least on the `colcon-cargo` side, I'm happy to start making the first tagged release (0.1.0?) unless anyone wants to take ownership of that @esteve, @jhdcs, @mxgrey.

`colcon-ros-cargo` is still pending a release on crates.io of `cargo-ament-build` and https://github.com/colcon/colcon-ros-cargo/pull/22

**Comment by esteve** [comment]
@luca-della-vedova I've just published a new relase of [cargo-ament-build](https://github.com/ros2-rust/cargo-ament-build)
