### ISSUE TITLE
Request for committer status

### ISSUE THREAD

**Issue by mxgrey** [colcon/colcon-cargo#31]
The cargo extensions for colcon are very important if the ROS community is to benefit from the growing Rust ecosystem.

Unfortunately these extensions have been unmaintained for a while, as there are several small but crucial bug fixes that have been sitting in PRs for months without review.

I'd like to request committer status for myself to help move these PRs along. It would also be good to get committer status on [colcon-ros-cargo](https://github.com/colcon/colcon-ros-cargo) so I can help there as well.

And to avoid a bus factor of 1, I would also recommend committer status for @luca-della-vedova who is also working very actively on bringing ROS and Rust together.

**Comment by nuclearsandwich** [comment]
FYI @lelongg (as the initial colcon-cargo admin).

The colcon org admins will grant this request in 7 days if there are no objections from current maintainers.

If current maintainers approve, we can grant the request earlier.

**Comment by mxgrey** [comment]
We're a healthy margin past the 7-day window with no objection. How do you feel about moving forward with granting permissions, @nuclearsandwich ?

**Comment by nuclearsandwich** [comment]
Invitations to join the org have been dispatched.
I have also removed inactive members in the interest of limiting access to active contributors.
Anyone who was removed and wishes to contribute in the future can request to be added back.

**Comment by mxgrey** [comment]
Looks like commit rights are working for both of us, thanks!

**Comment by luca-della-vedova** [comment]
> Invitations to join the org have been dispatched. I have also removed inactive members in the interest of limiting access to active contributors. Anyone who was removed and wishes to contribute in the future can request to be added back.
> 
> @mxgrey @luca-della-vedova please close this issue once you have accepted the invites and confirmed your access.

Hi @nuclearsandwich, it seems @esteve might have been removed but he is still an active member of the community and contributor, is it possible to add him back?

**Comment by esteve** [comment]
@luca-della-vedova thanks

@nuclearsandwich yeah, IIRC I had admin rights, but this ticket went under the radar. I probably missed all this because it was during Easter, from when it was opened to when it was closed. In any case, these extensions didn't have much activity, but are definitely not unmaintained

**Comment by nuclearsandwich** [comment]
The invitation has been sent out to @esteve to restore access. Apologies for the misunderstanding. In general I'd like to keep maintainer access to active contributors in order to re-verify maintainers returning from a break.

**Comment by esteve** [comment]
@nuclearsandwich no problem, thanks! :slightly_smiling_face:
